# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "citations", :force => true do |t|
    t.column "raw_string", :text
    t.column "authors", :text, :default => "--- []"
    t.column "title", :text
    t.column "year", :integer
    t.column "publisher", :text
    t.column "location", :text
    t.column "booktitle", :text
    t.column "journal", :text
    t.column "pages", :text
    t.column "volume", :text
    t.column "number", :text
    t.column "contexts", :text, :default => "--- []"
    t.column "tech", :text
    t.column "institution", :text
    t.column "editor", :text
    t.column "note", :text
    t.column "marker_type", :string
    t.column "marker", :string
  end

end
